---
- name: backup ale std config to local file
  shell: sftp -P {{ device_port }} -o {{ ssh_option }} {{ device_user }}@{{ ansible_host }}:/flash/certified/boot.cfg {{ backup_local_path }}/{{ backup_std_filename }}

- name: copy backup file to backup server
  shell: ncftpput -m backupftp {{ backup_srv_path }} {{ role_path }}/files/{{ backup_std_filename }}

- name: delete local backup file
  file:
    path: "{{ backup_local_path }}/{{ backup_std_filename }}"
    state: absent
